FROM didymusdidymus/picopad-builder:latest

LABEL maintainer="didymus@tuta.io"
LABEL version="1.0"
LABEL description="Quick compile whole directory of GB or GBC files"

ENTRYPOINT ["python3","/home/picoPad/picopad-builder-tools/ConvertGbFile.py","/GB-FILES/"]