name: Publsh Image to DockerHub

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: didymusdidymus/picopad-builder:latest, didymusdidymus/picopad-builder:${{ github.run_number }}
      - name: Build and push Dockerfile-autorun
        uses: docker/build-push-action@v4
        with:
          context: ./autorun
          push: true
          tags: didymusdidymus/picopad-builder-autorun:latest, didymusdidymus/picopad-builder-autorun:${{ github.run_number }}
